museum/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('museum_of_Nukus/', nks_museum, name='nks_museum'),
    path('collections/', collections, name='collections'),
    path('sources/', sources, name='sources'),
    path('catalogue/', catalogue, name='catalogue'),
    path('credits/', credits_p, name='credits'),
    path('copyright/', copyright_p, name='copyright'),
    path('contact/', contact, name='contact'),
    path('authors/', AuthorList.as_view(), name='author_list'),
    path('association/', AssociationList.as_view(), name='association_list'),
    path('education/', EducationList.as_view(), name='education_list'),
    path('institution/', InstitutionList.as_view(), name='institution_list'),
    path('author/<int:pk>/', author_detail, name='author_detail'),
    path('exhibit/<int:pk>/', exhibition_detail, name='exhibition_detail'),
    path('association/<int:pk>/', AssociationDetail.as_view(), name='association_detail'),
    path('education/<int:pk>/', EducationDetail.as_view(), name='education_detail'),
    path('institution/<int:pk>/', InstitutionDetail.as_view(), name='institution_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('set_theme/', set_theme, name='set_theme'),
]

museum/museum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

museum/main/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255, db_index=True, verbose_name='Имя художника')
    years_of_life = models.CharField(max_length=255, blank=True, verbose_name='Даты жизни')
    bio = models.TextField(blank=True, verbose_name='Биография')
    association = models.ManyToManyField('Association', blank=True, verbose_name='Группировка')
    education = models.ManyToManyField('Education', blank=True, verbose_name='Образование')
    institution = models.ManyToManyField('Institution', blank=True, verbose_name='Институция')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Художник'
        verbose_name_plural = 'Художники'
        ordering = ['name']


class Association(models.Model):
    name = models.CharField(max_length=255, verbose_name='Группировка')
    content = models.TextField(verbose_name='О группировке')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Группировка'
        verbose_name_plural = 'Группировки'
        ordering = ['name']


class Education(models.Model):
    name = models.CharField(max_length=255, verbose_name='Образование')
    content = models.TextField(verbose_name='Об учреждении')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Образовательное учреждение'
        verbose_name_plural = 'Образовательные учреждения'
        ordering = ['name']


class Institution(models.Model):
    name = models.CharField(max_length=255, verbose_name='Институция')
    content = models.TextField(verbose_name='Об институции')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Институция'
        verbose_name_plural = 'Институции'
        ordering = ['name']


class Exhibition(models.Model):
    name = models.CharField(max_length=255, db_index=True, verbose_name='Произведение')
    about = models.TextField(verbose_name='О произведении')
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Автор', related_name='exhibitions')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Произведение'
        verbose_name_plural = 'Произведении'
        ordering = ['name']


class ExhibitionPhoto(models.Model):
    photo = models.ImageField(upload_to="photos/%Y/%m/%d")
    exhibition = models.ForeignKey('Exhibition', on_delete=models.CASCADE, verbose_name='Произведение', related_name='photos')

    def __str__(self):
        return self.exhibition.name

    class Meta:
        verbose_name = 'Фотки произведения'
        verbose_name_plural = 'Фотки произведении'

museum/main/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from .models import *


def index(request):
    return render(request, 'main/index.html')


def nks_museum(request):
    return render(request, 'main/nks_museum.html')


def collections(request):
    return render(request, 'main/collections.html')


def sources(request):
    return render(request, 'main/sources.html')


def catalogue(request):
    return render(request, 'main/catalogue.html')


def credits_p(request):
    return render(request, 'main/credits.html')


def copyright_p(request):
    return render(request, 'main/copyright.html')


def contact(request):
    return render(request, 'main/contact.html')


class AuthorList(ListView):
    model = Author
    template_name = 'author_list.html'
    context_object_name = 'authors'

    def get_queryset(self):
        return Author.objects.all().order_by('name')


class AssociationList(ListView):
    model = Education
    template_name = 'association_list.html'
    context_object_name = 'association'

    def get_queryset(self):
        return Association.objects.all().order_by('name')


class EducationList(ListView):
    model = Education
    template_name = 'education_list.html'
    context_object_name = 'education'

    def get_queryset(self):
        return Education.objects.all().order_by('name')


class InstitutionList(ListView):
    model = Education
    template_name = 'institution_list.html'
    context_object_name = 'institution'

    def get_queryset(self):
        return Institution.objects.all().order_by('name')


def get_pk(queryset):
    list_of_pk = []
    for query in queryset:
        list_of_pk.append(query.pk)
    return list_of_pk


def author_detail(request, pk):
    template_name = 'main/author_detail.html'
    author = Author.objects.get(pk=pk)
    exhibitions = author.exhibitions.select_related('author').prefetch_related('photos')
    context = {
        'author': author,
        'exhibitions': exhibitions
    }
    return render(request, template_name, context)


def exhibition_detail(request, pk):
    template_name = 'main/exhibition_detail.html'
    exhibition = Exhibition.objects.get(pk=pk)
    exhib_photo = ExhibitionPhoto.objects.filter(exhibition=pk)

    context = {'exhib': exhibition, 'photo': exhib_photo}

    return render(request, template_name, context)


class AssociationDetail(DetailView):
    model = Association
    template_name = 'main/detail.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = Author.objects.filter(association=self.object.pk)
        return context


class EducationDetail(DetailView):
    model = Education
    template_name = 'main/detail.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = Author.objects.filter(education=self.object.pk)
        return context


class InstitutionDetail(DetailView):
    model = Institution
    template_name = 'main/detail.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = Author.objects.filter(institution=self.object.pk)
        return context


class SearchView(ListView):
    model = Author
    template_name = 'main/search.html'
    context_object_name = 'authors'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Author.objects.filter(
            Q(name__icontains=query) | Q(bio__icontains=query)
        )
        return object_list


def set_theme(request):
    theme = request.GET.get('theme', None)
    if theme == 'dark':
        response = redirect(request.META.get('HTTP_REFERER'))
        response.set_cookie('theme', 'dark')
        return response
    elif theme == 'light':
        response = redirect(request.META.get('HTTP_REFERER'))
        response.delete_cookie('theme')
        return response
    else:
        return redirect(request.META.get('HTTP_REFERER'))

museum/main/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    {% block title %}
    <title>СавицкийМузей</title>
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/png" href="{% static 'main/images/favicon.ico' %}"/>

</head>
<body class="d-flex flex-column h-100" data-bs-theme="{% if request.COOKIES.theme == 'dark' %}dark{% endif %}">
<header>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if not request.COOKIES.theme == 'dark' %}
            <a class="link-dark" href="{% url 'main:set_theme' %}?theme=dark&{{ request.GET.urlencode }}&cb={{ request.META.HTTP_HOST }}/{{ request.path }}"><i
                    class="bi bi-moon"></i></a>
            {% else %}
            <a class="link-light" href="{% url 'main:set_theme' %}?theme=light&{{ request.GET.urlencode }}&cb={{ request.META.HTTP_HOST }}/{{ request.path }}"><i
                    class="bi bi-sun"></i></a>
            {% endif %}
            <a class="navbar-brand text-end fw-light" href="{% url 'main:index' %}"><i class="bi bi-bank me-2"></i>СавицкийМузей</a>
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar"
                 aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title fw-normal" id="offcanvasNavbarLabel">Общественный каталог музея имени
                        И.В.Савицкого</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:nks_museum' %}">Нукусский
                                музей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                               href="{% url 'main:collections' %}">Коллекция</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:sources' %}">Источники</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Каталог
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'main:catalogue' %}">О каталоге</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'main:author_list' %}">Художники</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:association_list' %}">Группировки</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'main:education_list' %}">Образование</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:institution_list' %}">Институция</a>
                                </li>
                            </ul>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:credits' %}">Кредиты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:copyright' %}">Авторские права</a>
                        </li>
                    </ul>
                    <form class="d-flex mt-3" role="search" action="{% url 'main:search' %}" method="get">
                        <input name='q' class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </div>
    </nav>

</header>
<main>
    {% block content %}

    {% endblock %}
</main>
<footer class="footer mt-auto py-3 bg-body-tertiary">
    <div class="container">
            <span class="text-muted">Copyrights
                <a href="https://github.com/nearbad" class="text-muted">github.com/nearbad</a></span>
    </div>
</footer>
</body>
</html>

museum/main/templates/main/author_detail.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}
<title>СавицкийМузей - {{ author.name }}</title>
<link rel="stylesheet" type="text/css" href="{% static 'main/css/author_detail.css' %}">
{% endblock %}


{% block content %}

<div class="container mx-5 my-3">
    <div class="row">
        <div class="col-lg-12 col-10">
            <h5 class="display-5">{{ author.name }}</h5>
            <p>Даты жизни: <strong>{{ author.years_of_life }}</strong></p>
            {% if author.association.all %}
            <p>Группировка:
                {% for as in author.association.all %}
                <a href="{% url 'main:association_detail' as.pk %}" class="link-warning text-decoration-none">
                    {{ as.name }}; </a>
                {% endfor %}
            </p>
            {% endif %}
            {% if author.education.all %}
            <p class="fs-6"> Образование:
                {% for ed in author.education.all %}
                <a href="{% url 'main:education_detail' ed.pk %}" class="link-warning text-decoration-none">
                    {{ ed.name }}; </a>
                {% endfor %}
            </p>
            {% endif %}
            {% if author.institution.all %}
            <p>Институция:
                {% for ins in author.institution.all %}
                <a href="{% url 'main:institution_detail' ins.pk %}" class="link-warning text-decoration-none">
                    {{ ins.name }}; </a>
                {% endfor %}
            </p>
            {% endif %}
            <h6>Биография</h6>
            <div class="row">{{ author.bio|linebreaks }}</div>
            <div class="row">
                {% for ex in exhibitions %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 col-10">
                    <div class="hovereffect">
                        <img class="img-fluid img-thumbnail img-responsive" src="{{ ex.photos.first.photo.url }}"
                             alt="{{ ex.name }}">
                        <div class="overlay">
                            <h2>{{ ex.name }}</h2>
                            <a class="info" href="{% url 'main:exhibition_detail' ex.pk %}">
                                Перейти к произведению
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

museum/main/templates/main/author_list.html
{% extends 'layout/basic.html' %}

{% block content %}
<h4 class="display-5 mt-4 text-center"> СПИСОК ХУДОЖНИКОВ </h4>
<div class="container my-4">
    <div class="row text-center">
        <ul style="list-style: none">
            {% for author in authors %}
            <li class="my-2"><a class="text-decoration-none link-warning"
                                href="{% url 'main:author_detail' author.pk %}">{{ author.name }}</a>
                {{ author.bio|truncatechars:60 }}
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

museum/main/templates/main/contact.html
{% extends 'layout/basic.html' %}

{% block title %}
<title>СавицкийМузей - Связаться с нами</title>
{% endblock %}

{% block content %}
<div class="display-4 m-4 text-center">
    КОНТАКТЫ
</div>
<div class="container">
    <p><strong>E-mail<br/></strong><a class="link-warning" href="mailto:heritalert@gmail.com">heritalert@gmail.com<br/></a>N.B.:
        Все вопросы,
        связанные с Музеем, такие как организация выставок, посещение Музея, вопросы о публикации изображений и т.д.,
        необходимо адресовывать напрямую Музею. Указанный е-мейл не является е-мейлом Музея, и <em>Alerte
            H&eacute;ritage</em> не сможет пересылать сообщения Музею.</p>
    <p><strong>Сайт&nbsp;</strong><br/>Русская версия : <a class="link-warning" href="https://www.alerteheritage.org/"
                                                           target="_blank">www.alerteheritage.org</a><br/>Version
        fran&ccedil;aise :&nbsp;<a class="link-warning" href="http://heritalert.wixsite.com/alert-fr" target="_blank">heritalert.wixsite.com/alert-fr</a>
    </p>
    <p><strong>Facebook</strong><br/><a class="link-warning" href="https://www.facebook.com/alerteheritage/"
                                        target="_blank">facebook.com/alerteheritage/</a><br/><br/>
</div>
{% endblock %}

museum/main/templates/main/credits.html
{% extends 'layout/basic.html' %}

{% block title %}
<title>СавицкийМузей - Кредиты</title>
{% endblock %}

{% block content %}
<div class="display-4 m-4 text-center">
    КРЕДИТЫ
</div>
<div class="container">
    <p class="my-2" style="text-align: justify;">
        Реализация проекта стала возможной прежде всего благодаря гражданским усилиям заинтересованных лиц, которые
        согласились помочь нам в фотофиксации картин в самом Нукусском музее и на других выставочных площадках, а также
        в нахождении и сканировании каталогов с работами из этого собрания.
    </p>
    <p class="my-2" style="text-align: justify;">
        Мы искренне благодарим за содействие и помощь в этой работе Анн Боти (Женева), Зухру Касымову (Чикаго), Ксению
        Крутову (Москва), Азизу Наурузбаеву (Ташкент) и Даниила Кислова (Москва).
    </p>
    <p class="my-2" style="text-align: justify;">
        Мы также адресуем наши слова благодарности за доброжелательное сотрудничество и предоставление ценных сведений
        Маринике Бабаназаровой, руководившей Нукусским музеем с 1984 по 2015 годы, и Гульбахор Изентаевой, нынешней
        директрисе Музея.
    </p>
    <p class="my-2" style="text-align: justify;">
        Мы очень признательны программисту Алексею Барташевичу (Санкт-Петербург) за верстку этого сайта и создание
        внутренней базы данных проекта.
    </p>
    <p class="my-2" style="text-align: justify;">
        Брендинговое агентство Асгард-дизайн (Санкт-Петербург) в лице его руководителей Давида Авакяна и Ольги Лосевой
        всегда было на связи для консультаций, неизменно точных и полезных.
    </p>
    <p class="my-2" style="text-align: justify;">
        Мы также выражаем нашу благодарность всем членам <a target="_blank" href="https://www.alerteheritage.org/o-nas"
                                                            class="link-warning"> Наблюдательного совета </a>Обсерватории
        <a target="_blank" href="https://www.alerteheritage.org/" class="link-warning">Alerte Héritage</a>, чья
        поддержка и советы помогли нам осуществить этот проект.
    </p>
    <p class="my-2" style="text-align: justify;">
        Борис Чухович (президент) и Светлана Горшенина (генеральный секретарь)
        Обсерватория <a target="_blank" href="https://www.alerteheritage.org/" class="link-warning">Alerte Héritage</a>
    </p>
</div>
{% endblock %}

museum/main/templates/main/detail.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}
<title>СавицкийМузей - {{ object.name }}</title>
{% endblock %}

{% block content %}
<div class="container mx-5 my-3">
    <div class="row">
        <div class="col-lg-12 col-10">
            <h5 class="display-5">{{ object.name }}</h5>
            <div class="row">{{ object.content|linebreaks }}</div>
        </div>
    </div>
</div>
<div class="container mx-5 my-3">
    <div class="col-lg-12 col-8">
        <div class="display-6 fs-4 text-center m-3">ХУДОЖНИКИ</div>
        <div class="row text-center">
            {% for author in authors %}
            <a href="{% url 'main:author_detail' author.pk %}" class="text-decoration-none link-warning">
                {{ author.name }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

museum/main/templates/main/education_list.html
{% extends 'layout/basic.html' %}

{% block title %}
<title>СавицкийМузей - Список образовательных учреждений</title>
{% endblock %}

{% block content %}
<h4 class="display-5 mt-4 text-center">СПИСОК ОБРАЗОВАТЕЛЬНЫХ УЧРЕЖДЕНИЙ</h4>
<div class="container my-4">
    <div class="row text-center">
        <ul style="list-style: none">
            {% for ed in education %}
            <li class="my-2"><a class="text-decoration-none link-warning"
                                href="{% url 'main:education_detail' ed.pk %}">{{ ed.name }}</a>
                <p class="text-muted">{{ ed.content|truncatechars:60 }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

museum/main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-9">
            <ul class="nav nav-fill my-3">
                <li class="nav-item">
                    <a class="nav-link link-info" aria-current="page" href="{% url 'main:author_list' %}">Художники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-info" href="{% url 'main:association_list' %}">Группировки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-info" href="{% url 'main:contact' %}">Контакты</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-3 col-4 my-3 d-none d-lg-block d-xl-block">
            <form class="d-flex" role="search"
                  action="{% url 'main:search' %}"
                  method="get">
                <input name='q' class="form-control me-1" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</div>

<div class="mx-4">
    <div class="row rounded d-none d-md-block d-lg-block d-xl-block">
        <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <a href="{% url 'main:nks_museum' %}">
                        <img src="{% static 'main/images/1.jpg' %}" class="d-block w-100" alt="...">
                    </a>
                </div>
                <div class="carousel-item">
                    <a href="{% url 'main:author_list' %}">
                        <img src="{% static 'main/images/2.jpg' %}" class="d-block w-100" alt="...">
                    </a>
                </div>
                <div class="carousel-item">
                    <a href="#">
                        <img src="{% static 'main/images/3.jpg' %}" class="d-block w-100" alt="...">
                    </a>
                </div>
                <div class="carousel-item">
                    <a href="{% url 'main:author_detail' 5 %}">
                        <img src="{% static 'main/images/4.jpg' %}" class="d-block w-100" alt="...">
                    </a>
                </div>
                <div class="carousel-item">
                    <a href="{% url 'main:author_detail' 6 %}">
                        <img src="{% static 'main/images/5.jpg' %}" class="d-block w-100" alt="...">
                    </a>
                </div>
                <div class="carousel-item">
                    <a href="#"><img src="{% static 'main/images/6.jpg' %}" class="d-block w-100" alt="...">
                    </a>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{% static 'main/images/7.jpg' %}" class="img-fluid" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text">Нукусский музей создан в 1966 году по инициативе художника и коллекционера
                        Игоря Витальевича Савицкого, во взаимодействии с поддержавшими его деятельность представителями
                        руководящих органов Каракалпакской АССР: обкома КП, Совета министров и Академии...</p>
                    <p class="card-text"><small class="text-muted"><a href="{% url 'main:nks_museum' %}">Читать далее
                        >></a></small></p>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{% static 'main/images/8.jpg' %}" class="img-fluid" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text">Общественный открытый каталог Нукусского музея представляет собой виртуальную
                        базу данных, в которой фигурируют все известные нам и публиковавшиеся произведения из коллекции
                        И.В. Савицкого. Содержание каталога структурировано по художникам, арт-группировкам,
                        институциям, учебным заведениям, ключевым словам и пр., что позволяет быстро осуществлять
                        навигационный поиск.</p>
                    <p class="card-text"><small class="text-muted"><a href="{% url 'main:author_list' %}">Перейти к
                        списку художников >></a>
                    </small></p>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{% static 'main/images/9.jpg' %}" class="img-fluid" alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text">История формирования коллекции началась до официального основания Нукусского
                        музея. Еще в конце 1950-х – начале 1960-х гг. Игорь Савицкий занимался коллекционированием
                        предметов каракалпакского народно-прикладного искусства в Каракалпакском филиале АН Узбекистана.
                        Им также был сформирован археологический отряд, который занимался сбором предметов искусства
                        древнего Хорезма. Таким образом, первоначальным ядром музейной коллекции стало древнее и
                        народное искусство приаральского региона, на территории которого сегодня находится
                        Каракалпакстан. </p>
                    <p class="card-text"><small class="text-muted"><a href="{% url 'main:collections' %}">Читать далее
                        >></a></small></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

museum/main/templates/main/institution_list.html
{% extends 'layout/basic.html' %}

{% block title %}
<title>СавицкийМузей - Список институций</title>
{% endblock %}

{% block content %}
<h4 class="display-5 mt-4 text-center">СПИСОК ИНСТИТУЦИЙ</h4>
<div class="container my-4">
    <div class="row text-center">
        <ul style="list-style: none">
            {% for ins in institution %}
            <li class="my-2"><a class="text-decoration-none link-warning"
                                href="{% url 'main:institution_detail' ins.pk %}">{{ ins.name }}</a>
                <p class="text-muted">{{ ins.content|truncatechars:60 }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

museum/main/templates/main/search.html
{% extends 'layout/basic.html' %}

{% block title %}
<title>СавицкийМузей - Результаты запроса</title>
{% endblock %}

{% block content %}

{% if authors %}
<h4 class="display-5 mt-4 text-center"> Результаты запроса </h4>
<div class="container my-4">
    <div class="row text-center">
        <ul style="list-style: none">
            {% for author in authors %}
            <li class="my-2"><a class="text-decoration-none link-warning"
                                href="{% url 'main:author_detail' author.pk %}">{{ author.name }}</a>
                {{ author.bio|truncatechars:60 }}
                {% if author.education.name %}
                <p class="text-muted">{{ author.education.name }}</p>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% else %}
<h4 class="display-5 text-center text-muted mt-4">
    Ничего не найдено...
</h4>
{% endif %}
{% endblock %}